name: Build and Deploy to Bunny CDN

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build & Deploy
    runs-on: ubicloud-standard-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .image-cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build with Node
        run: |
          npm ci
          npx @11ty/eleventy

      - name: Format with Prettier
        run: npm run format

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Set deployment environment
        id: deployment_env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "storage_zone_name=${{ secrets.BUNNY_PRODUCTION_STORAGE_ZONE_NAME }}" >> $GITHUB_OUTPUT
            echo "storage_zone_password=${{ secrets.BUNNY_PRODUCTION_STORAGE_ZONE_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "pull_zone_id_deploy=${{ secrets.BUNNY_PRODUCTION_PULL_ZONE_ID }}" >> $GITHUB_OUTPUT
          else
            echo "storage_zone_name=${{ secrets.BUNNY_STAGING_STORAGE_ZONE_NAME }}" >> $GITHUB_OUTPUT
            echo "storage_zone_password=${{ secrets.BUNNY_STAGING_STORAGE_ZONE_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "pull_zone_id_deploy=${{ secrets.BUNNY_STAGING_PULL_ZONE_ID }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.0.6
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: _site
          storage-endpoint: "https://storage.bunnycdn.com"
          storage-zone-name: ${{ steps.deployment_env.outputs.storage_zone_name }}
          storage-zone-password: ${{ steps.deployment_env.outputs.storage_zone_password }}
          concurrency: "5"
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: ${{ steps.deployment_env.outputs.pull_zone_id_deploy }}
          replication-timeout: "15000"

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
      - name: Send failure notification
        uses: NiNiyas/ntfy-action@master
        with:
          url: 'https://ntfy.sh'
          topic: ${{ secrets.NTFY_TOPIC }}
